name: Docker Image CI

on:
  push:
    branches:
      - "small-image"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */3 * * *'

env:
  REGISTRY: ghcr.io

jobs:

  build-push:
    runs-on: ubuntu-latest

    steps:

    - name: Check Out Repo
      uses: actions/checkout@v4

    # arm64 specific
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to registry
      uses: docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner.toLowerCase() }}/libremdb:latest
